# Generated by Django 3.2.10 on 2022-05-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
